import { Type } from '@angular/core';
import { AboutmeComponent } from '../features/aboutme/aboutme.component';
import { ContactComponent } from '../features/contact/contact.component';
import { ProjectsComponent } from '../features/projects/projects.component';
import { StackComponent } from '../features/stack/stack.component';

export const COMPONENT_MAP: { keyword: string; component: Type<any> }[] = [
  // About Me 
  { keyword: 'about me', component: AboutmeComponent },
  { keyword: 'about', component: AboutmeComponent },
  { keyword: 'who are you', component: AboutmeComponent },
  { keyword: 'bio', component: AboutmeComponent },
  { keyword: 'background', component: AboutmeComponent },
  { keyword: 'personal information', component: AboutmeComponent },
  { keyword: 'introduction', component: AboutmeComponent },
  { keyword: 'self', component: AboutmeComponent },
  { keyword: 'self introduction', component: AboutmeComponent },
  { keyword: 'who i am', component: AboutmeComponent },
  { keyword: 'my story', component: AboutmeComponent },
  { keyword: 'myself', component: AboutmeComponent },
  { keyword: 'details about me', component: AboutmeComponent },
  { keyword: 'my background', component: AboutmeComponent },
  { keyword: 'get to know me', component: AboutmeComponent },
  { keyword: 'personality', component: AboutmeComponent },
  { keyword: 'career', component: AboutmeComponent },
  { keyword: 'life', component: AboutmeComponent },
  { keyword: 'who is this', component: AboutmeComponent },
  { keyword: 'introduction to myself', component: AboutmeComponent },
  { keyword: 'personal journey', component: AboutmeComponent },
  { keyword: 'life journey', component: AboutmeComponent },
  { keyword: 'who i am as a person', component: AboutmeComponent },
  { keyword: 'know me better', component: AboutmeComponent },
  { keyword: 'information about me', component: AboutmeComponent },
  { keyword: 'meet me', component: AboutmeComponent },
  { keyword: 'meet the person', component: AboutmeComponent },
  { keyword: 'who i am', component: AboutmeComponent },
  { keyword: 'what about me', component: AboutmeComponent },
  { keyword: 'my personal details', component: AboutmeComponent },
  { keyword: 'personal history', component: AboutmeComponent },
  { keyword: 'self story', component: AboutmeComponent },
  { keyword: 'all about me', component: AboutmeComponent },
  { keyword: 'my profile', component: AboutmeComponent },
  { keyword: 'personal details', component: AboutmeComponent },
  { keyword: 'profile', component: AboutmeComponent },
  { keyword: 'who i am and what i do', component: AboutmeComponent },
  { keyword: 'getting to know me', component: AboutmeComponent },
  { keyword: 'meet the developer', component: AboutmeComponent },
  { keyword: 'what defines me', component: AboutmeComponent },
  { keyword: 'all you need to know about me', component: AboutmeComponent },
  { keyword: 'who i am in brief', component: AboutmeComponent },
  { keyword: 'my experiences', component: AboutmeComponent },
  { keyword: 'my skills', component: AboutmeComponent },
  { keyword: 'my career path', component: AboutmeComponent },
  { keyword: 'my professional story', component: AboutmeComponent },
  { keyword: 'life story', component: AboutmeComponent },
  { keyword: 'who is the creator', component: AboutmeComponent },
  { keyword: 'a bit about me', component: AboutmeComponent },
  { keyword: 'my biography', component: AboutmeComponent },
  { keyword: 'let me introduce myself', component: AboutmeComponent },
  { keyword: 'here is who i am', component: AboutmeComponent },
  { keyword: 'find out about me', component: AboutmeComponent },
  { keyword: 'all my information', component: AboutmeComponent },
  { keyword: 'introducing myself', component: AboutmeComponent },
  { keyword: 'discover me', component: AboutmeComponent },
  { keyword: 'self-introduction', component: AboutmeComponent },
  { keyword: 'a quick look at me', component: AboutmeComponent },
  { keyword: 'personal summary', component: AboutmeComponent },
  { keyword: 'short bio', component: AboutmeComponent },
  { keyword: 'bio info', component: AboutmeComponent },
  { keyword: 'who am i in depth', component: AboutmeComponent },
  { keyword: 'how i became me', component: AboutmeComponent },
  { keyword: 'about the developer', component: AboutmeComponent },
  { keyword: 'background details', component: AboutmeComponent },
  { keyword: 'why i do what i do', component: AboutmeComponent },
  { keyword: 'how i got here', component: AboutmeComponent },
  { keyword: 'personal philosophy', component: AboutmeComponent },
  { keyword: 'life lessons', component: AboutmeComponent },
  { keyword: 'inspirations', component: AboutmeComponent },
  { keyword: 'self-reflection', component: AboutmeComponent },
  { keyword: 'life principles', component: AboutmeComponent },
  { keyword: 'personal values', component: AboutmeComponent },
  { keyword: 'personal motivations', component: AboutmeComponent },

  // Projects 
  { keyword: 'projects', component: ProjectsComponent },
  { keyword: 'portfolio', component: ProjectsComponent },
  { keyword: 'work', component: ProjectsComponent },
  { keyword: 'what i have done', component: ProjectsComponent },
  { keyword: 'my projects', component: ProjectsComponent },
  { keyword: 'my work', component: ProjectsComponent },
  { keyword: 'completed projects', component: ProjectsComponent },
  { keyword: 'project showcase', component: ProjectsComponent },
  { keyword: 'my portfolio', component: ProjectsComponent },
  { keyword: 'recent work', component: ProjectsComponent },
  { keyword: 'past work', component: ProjectsComponent },
  { keyword: 'showcase', component: ProjectsComponent },
  { keyword: 'accomplishments', component: ProjectsComponent },
  { keyword: 'achievements', component: ProjectsComponent },
  { keyword: 'finished projects', component: ProjectsComponent },
  { keyword: 'previous projects', component: ProjectsComponent },
  { keyword: 'done work', component: ProjectsComponent },
  { keyword: 'project details', component: ProjectsComponent },
  { keyword: 'work history', component: ProjectsComponent },
  { keyword: 'completed tasks', component: ProjectsComponent },
  { keyword: 'project examples', component: ProjectsComponent },
  { keyword: 'what i built', component: ProjectsComponent },
  { keyword: 'projects i created', component: ProjectsComponent },
  { keyword: 'portfolio items', component: ProjectsComponent },
  { keyword: 'work portfolio', component: ProjectsComponent },
  { keyword: 'what i created', component: ProjectsComponent },
  { keyword: 'projects i worked on', component: ProjectsComponent },
  { keyword: 'my recent projects', component: ProjectsComponent },
  { keyword: 'completed tasks', component: ProjectsComponent },
  { keyword: 'how i work', component: ProjectsComponent },
  { keyword: 'development projects', component: ProjectsComponent },
  { keyword: 'projects list', component: ProjectsComponent },
  { keyword: 'my creations', component: ProjectsComponent },
  { keyword: 'accomplished work', component: ProjectsComponent },
  { keyword: 'finished tasks', component: ProjectsComponent },
  { keyword: 'project accomplishments', component: ProjectsComponent },
  { keyword: 'work showcase', component: ProjectsComponent },
  { keyword: 'portfolio showcase', component: ProjectsComponent },
  { keyword: 'work examples', component: ProjectsComponent },

  // Stack 
  { keyword: 'stack', component: StackComponent },
  { keyword: 'technologies', component: StackComponent },
  { keyword: 'tools', component: StackComponent },
  { keyword: 'skills', component: StackComponent },
  { keyword: 'frameworks', component: StackComponent },
  { keyword: 'technological stack', component: StackComponent },
  { keyword: 'technology stack', component: StackComponent },
  { keyword: 'tech stack', component: StackComponent },
  { keyword: 'technologies i use', component: StackComponent },
  { keyword: 'my tech stack', component: StackComponent },
  { keyword: 'programming stack', component: StackComponent },
  { keyword: 'my tools', component: StackComponent },
  { keyword: 'tools i use', component: StackComponent },
  { keyword: 'technology tools', component: StackComponent },
  { keyword: 'what i use', component: StackComponent },
  { keyword: 'used technologies', component: StackComponent },
  { keyword: 'used frameworks', component: StackComponent },
  { keyword: 'what i build with', component: StackComponent },
  { keyword: 'used tech stack', component: StackComponent },
  { keyword: 'my development tools', component: StackComponent },
  { keyword: 'development stack', component: StackComponent },
  { keyword: 'used programming languages', component: StackComponent },
  { keyword: 'what tools i use', component: StackComponent },
  { keyword: 'programming tools', component: StackComponent },
  { keyword: 'frameworks i use', component: StackComponent },
  { keyword: 'stack of technologies', component: StackComponent },
  { keyword: 'tech skills', component: StackComponent },
  { keyword: 'my programming tools', component: StackComponent },

  // Contact 
  { keyword: 'contact', component: ContactComponent },
  { keyword: 'reach me', component: ContactComponent },
  { keyword: 'message', component: ContactComponent },
  { keyword: 'email', component: ContactComponent },
  { keyword: 'how to contact me', component: ContactComponent },
  { keyword: 'send a message', component: ContactComponent },
  { keyword: 'get in touch', component: ContactComponent },
  { keyword: 'connect with me', component: ContactComponent },
  { keyword: 'contact me', component: ContactComponent },
  { keyword: 'contact form', component: ContactComponent },
  { keyword: 'talk to me', component: ContactComponent },
  { keyword: 'reach out', component: ContactComponent },
  { keyword: 'email me', component: ContactComponent },
  { keyword: 'talk', component: ContactComponent },
  { keyword: 'send an email', component: ContactComponent },
  { keyword: 'contact details', component: ContactComponent },
  { keyword: 'contact info', component: ContactComponent },
  { keyword: 'send me a message', component: ContactComponent },
  { keyword: 'message me', component: ContactComponent },
  { keyword: 'contact address', component: ContactComponent },
  { keyword: 'get connected', component: ContactComponent },
  { keyword: 'contact request', component: ContactComponent },
  { keyword: 'get in touch with me', component: ContactComponent },
  { keyword: 'how to send a message', component: ContactComponent },
  { keyword: 'reach out to me', component: ContactComponent },
  { keyword: 'how to reach me', component: ContactComponent },
  { keyword: 'contact info', component: ContactComponent },
];
