export const projects = [
  {
    company: 'Accenture',
    client: 'Ministerio de Sanidad de España',
    task: 'Task',
    detailsTask: [
      '- Re-engineer old apps.',
      '- Create functional documents.',
      '- Review old versions.',
      '- Fix development bugs.',
      '- Write technical docs.',
      '- Design responsive layouts.',
      '- Integrate APIs with REST.',
      '- Optimize front-end performance.',
      '- Test and debug cross-browser.',
    ],

    tech: 'Tech',
    detailsTech: [
      'Angular 15: Frontend framework.',
      'HTML5: Web content structure.',
      'SCSS: Enhanced CSS styling.',
      'Bootstrap: Responsive design UI.',
      'PrimeNG: Angular UI library.',
      'Postman: API testing tool.',
      'Jenkins: CI/CD automation.',
      'Redmine: Project management tool.',
      'Apache SVN: Version control.',
    ],
  },
  {
    company: 'Accenture',
    client: 'El Corte Inglés',
    task: 'Task',
    detailsTask: [
      '- Develop new features and analysis.',
      '- Client and supplier coordination.',
      '- Web app maintenance.',
      '- Resolve production issues.',
      '- On-call incident support.',
      '- System improvements.',
      '- Team collaboration.',
      '- Ensure stability and performance.',
      '- Debug production issues quickly.',
    ],
    tech: 'Tech',
    detailsTech: [
      'Angular 8: Frontend framework.',
      'HTML5: Web content structure.',
      'CSS: Web design styles.',
      'Postman: API testing tool.',
      'Jira: Task tracking tool.',
      'Confluence: Documentation tool.',
      'Kibana: Log analysis tool.',
      'SmartIT: Incident management.',
      'Clarive: DevOps lifecycle tool.',
    ],
  },
  {
    company: 'Accenture',
    client: 'RENFE',
    task: 'Task',
    detailsTask: [
      '- Responsive layouts with HTML, CSS, Bootstrap.',
      '- Optimized databases and SQL queries.',
      '- Debugged and maintained Java code.',
      '- Integrated front-end and back-end systems.',
      '- Improved stability and response times.',
      '- Resolved technical issues with the team.',
      '- Documented updates and fixes.',
      '- Added new features and maintained existing ones.',
      '- Conducted regular production testing.',
    ],
    tech: 'Tech',
    detailsTech: [
      'Java 8: Backend framework.',
      'HTML5: Web content structure.',
      'CSS: Web design styles.',
      'Postman: API testing tool.',
      'SQL: Database management.',
      'JavaScript: Interactive web elements.',
      'Remedy: Incident management tool.',
      'Confluence: Documentation tool.',
      'Jira: Task tracking tool.',
    ],
  },
];
